---
title: "Student Performance Factors Analysis App"
subtitle: "Kaelin Silas"
output: html_document
date: "2024-10-17"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(ggplot2)
library(knitr)
library(tidyverse)
library(DT)
library(plotly)
library(slider)
library(shiny)
library(patchwork)
library(ggpattern)
```

```{r, include=FALSE}
spf_df = read_csv("https://raw.githubusercontent.com/kaelinmsilas/Homework2/refs/heads/main/StudentPerformanceFactors.csv")
colnames(spf_df)
spf_df = na.omit(spf_df)
spf_df$Family_Income = factor(spf_df$Family_Income, levels = c("Low", "Medium", "High"))
spf_df$Motivation_Level = factor(spf_df$Motivation_Level, levels = c("High", "Medium", "Low"))
  
```

```{r}
reset_selection <- function(x, brush) {
  brushedPoints(x, brush, allRows = TRUE)$selected_
}
max_hist_y <- spf_df %>%
  count(Exam_Score) %>%
  pull(n) %>%
  max()

histogram <- function(spf_df) {
  spf_df %>%
    ggplot() +
    geom_bar(aes(x = Exam_Score), fill = "deepskyblue3", width = 1) + 
    scale_y_continuous(limits = c(0, max_hist_y)) +
    labs(x = "Exam Scores", y = "# of Students", title = "Exam Score Distribution")
}

bargraph <- function(spf_df, selected_) {
  spf_df %>%
    filter(selected_) %>%
    ggplot(aes(x = Family_Income, fill = Motivation_Level, pattern = Motivation_Level)) +
    geom_bar_pattern(position = "stack") +
    scale_fill_manual(values = c("High" = "mediumseagreen", "Medium" = "gold1", "Low" = "brown3")) +
    labs(x = "Family Income", y = "# of Students", title = "Family Income and Motivation Level", fill = "Motivation Level", pattern = "Motivation Level")
}

data_table <- function(spf_df, selected_) {
  spf_df %>%
    filter(selected_) %>%
    select(Exam_Score, Family_Income, School_Type, Access_to_Resources, Parental_Involvement, Motivation_Level)
}

ui <- fluidPage(
  titlePanel("Analyzing Student Performance"),
  h5("Student performance is measured in exam scores. Factors that we will examine include school type(public or private), family income, access to resources, parental involvement, and motivational level"),
  
  fluidRow(
    column(12, checkboxGroupInput("School_Type", "Select School Type:",
                                   choices = list("Public" = "Public", "Private" = "Private"),
                                   selected = c("Public", "Private")))
  ),
  
  fluidRow(
    column(6, plotOutput("histogram", brush = brushOpts("plot_brush", direction = "x"))),
    column(6, plotOutput("bargraph"))
  ),
  fluidRow(
    column(12, htmlOutput("annotation"))
  ),
  fluidRow(
    column(12, DTOutput("table"))
  )
)

server <- function(input, output) {
  filtered_data <- reactive({
    spf_df %>%
      filter(School_Type %in% input$School_Type)
  })
  
  selected <- reactiveVal(rep(TRUE, nrow(spf_df)))
  
  observeEvent(
    input$plot_brush,
    selected(reset_selection(filtered_data(), input$plot_brush))
  )
  
  output$histogram <- renderPlot({
    histogram(filtered_data())
  })
  
  output$bargraph <- renderPlot({
    bargraph(filtered_data(), selected())
  })
  
  output$annotation <- renderUI({
    renderText("For a closer look, here is the corresponding data arranged from lowest to highest exam score: ")
  })
  
  output$table <- renderDataTable({
    data_table(filtered_data(), selected())
  })
}

shinyApp(ui, server)
```
